import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createServer} from 'node:net';
import {fileURLToPath} from 'node:url';
let server,directory,base,port,alex,bob,charlie,post,thread;
async function start(){server=spawn(process.execPath,['server/index.mjs'],{cwd:fileURLToPath(new URL('../',import.meta.url)),env:{...process.env,SOCIAL_DATA_DIR:directory,PORT:String(port),DEMO_MODE:'1'},stdio:['ignore','pipe','pipe']});let output='';server.stderr.on('data',s=>output+=s);await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(new Error('Server did not start: '+output)),10000);server.stdout.on('data',s=>{if(String(s).includes('is ready')){clearTimeout(timeout);resolve();}});server.on('exit',code=>{clearTimeout(timeout);reject(new Error(`Server exited ${code}: ${output}`));});});}
async function stop(){if(!server||server.exitCode!==null)return;await new Promise(resolve=>{server.once('exit',resolve);server.kill('SIGTERM');});}
async function call(path,{as,method='GET',body,expect=200,headers={}}={}){const response=await fetch(base+'/api'+path,{method,headers:{...(as?{Cookie:as.cookie}:{}),...(body!==undefined?{'Content-Type':'application/json'}:{}),...headers},body:body!==undefined?JSON.stringify(body):undefined});const payload=await response.json();assert.equal(response.status,expect,`${method} ${path}: ${JSON.stringify(payload)}`);return {...payload,cookie:response.headers.get('set-cookie')?.split(';')[0]};}
before(async()=>{directory=await mkdtemp(join(tmpdir(),'social-test-'));const socket=createServer();await new Promise(resolve=>socket.listen(0,'127.0.0.1',resolve));port=socket.address().port;await new Promise(resolve=>socket.close(resolve));base=`http://127.0.0.1:${port}`;await start();alex=await call('/auth/demo',{method:'POST'});bob=await call('/auth/register',{method:'POST',body:{name:'Bob Tester',handle:'bob_test',password:'  password with spaces  '},expect:201});charlie=await call('/auth/register',{method:'POST',body:{name:'Charlie Tester',handle:'charlie_test',password:'charlie-password'},expect:201});});
after(async()=>{await stop();if(directory)await rm(directory,{recursive:true,force:true});});
test('authentication requires real credentials and never leaks password hashes',async()=>{await call('/posts',{expect:401});await call('/auth/login',{method:'POST',body:{handle:'bob_test',password:'wrong'},expect:401});await call('/auth/register',{method:'POST',body:{name:'Duplicate',handle:'BOB_TEST',password:'password-again'},expect:409});const session=await call('/session',{as:alex});assert.equal(session.user.handle,'alex');assert.equal(session.user.password,undefined);assert.equal(session.user.salt,undefined);const login=await call('/auth/login',{method:'POST',body:{handle:'bob_test',password:'  password with spaces  '}});assert.equal(login.user.id,bob.user.id);});
test('posts persist, can be edited only by their author, and reject empty/oversized content',async()=>{await call('/posts',{as:bob,method:'POST',body:{text:'   '},expect:400});await call('/posts',{as:bob,method:'POST',body:{text:'x'.repeat(3001)},expect:400});post=(await call('/posts',{as:bob,method:'POST',body:{text:'A real persistent test post.'},expect:201})).post;assert.equal(post.author.id,bob.user.id);assert.equal(post.likes,0);await call(`/posts/${post.id}`,{as:alex,method:'PATCH',body:{text:'Unauthorised'},expect:403});await call(`/posts/${post.id}`,{as:alex,method:'DELETE',expect:403});post=(await call(`/posts/${post.id}`,{as:bob,method:'PATCH',body:{text:'An edited persistent test post.'}})).post;assert.match(post.text,/edited/);});
test('likes, bookmarks and comments have actual persisted counts and cannot be double-counted',async()=>{for(let i=0;i<2;i++)await call(`/posts/${post.id}/like`,{as:alex,method:'POST',body:{active:true}});let p=(await call(`/posts/${post.id}`,{as:alex})).post;assert.equal(p.likes,1);assert.equal(p.liked,true);await call(`/posts/${post.id}/bookmark`,{as:alex,method:'POST',body:{active:true}});assert.ok((await call('/posts?saved=1',{as:alex})).posts.some(p=>p.id===post.id));const c=await call(`/posts/${post.id}/comments`,{as:alex,method:'POST',body:{text:'This comment is saved too.'},expect:201});assert.equal(c.post.commentCount,1);assert.equal((await call(`/posts/${post.id}/comments`,{as:bob})).comments[0].author.id,alex.user.id);await call(`/comments/${c.comment.id}`,{as:charlie,method:'DELETE',expect:403});await call(`/comments/${c.comment.id}`,{as:alex,method:'DELETE'});assert.equal((await call(`/posts/${post.id}`,{as:bob})).post.commentCount,0);});
test('friend requests are directed, accepted by the recipient, and reflected in friends feed',async()=>{await call(`/friends/${alex.user.id}`,{as:bob,method:'POST',body:{action:'request'}});const incoming=(await call('/people',{as:alex})).people.find(p=>p.id===bob.user.id);assert.equal(incoming.relation,'incoming');await call(`/friends/${alex.user.id}`,{as:bob,method:'POST',body:{action:'accept'},expect:400});await call(`/friends/${bob.user.id}`,{as:alex,method:'POST',body:{action:'accept'}});assert.equal((await call('/people',{as:alex})).people.find(p=>p.id===bob.user.id).relation,'friends');assert.ok((await call('/posts?scope=friends',{as:alex})).posts.some(p=>p.id===post.id));assert.ok((await call('/notifications',{as:bob})).notifications.some(n=>n.type==='friend_accepted'));});
test('private messages use separate conversations, real read receipts and no fabricated replies',async()=>{thread=(await call('/conversations',{as:alex,method:'POST',body:{peerId:bob.user.id},expect:201})).id;assert.equal((await call('/conversations',{as:bob,method:'POST',body:{peerId:alex.user.id}})).id,thread);await call(`/conversations/${thread}/messages`,{as:charlie,expect:404});await call(`/conversations/${thread}/messages`,{as:charlie,method:'POST',body:{text:'Intrusion'},expect:404});const sent=await call(`/conversations/${thread}/messages`,{as:alex,method:'POST',body:{text:'Hello Bob, this is a real message.'},expect:201});assert.equal(sent.message.read,false);const before=(await call('/conversations',{as:bob})).conversations.find(c=>c.id===thread);assert.equal(before.unread,1);const received=await call(`/conversations/${thread}/messages`,{as:bob});assert.equal(received.messages.length,1);assert.equal(received.messages[0].text,'Hello Bob, this is a real message.');assert.equal((await call('/conversations',{as:bob})).conversations.find(c=>c.id===thread).unread,0);assert.equal((await call(`/conversations/${thread}/messages`,{as:alex})).messages[0].read,true);await call(`/conversations/${thread}/messages`,{as:bob,method:'POST',body:{text:'And this is a real reply.'},expect:201});assert.equal((await call(`/conversations/${thread}/messages`,{as:alex})).messages.length,2);});
test('upload validation rejects disguised files and enforces ownership',async()=>{await call('/uploads',{as:bob,method:'POST',body:{data:'data:image/png;base64,'+Buffer.from('not an image at all').toString('base64')},expect:400});const png='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jX1kAAAAASUVORK5CYII=';const uploaded=await call('/uploads',{as:bob,method:'POST',body:{data:png},expect:201});await call('/posts',{as:alex,method:'POST',body:{text:'Stolen image',image:uploaded.path},expect:400});const imagePost=await call('/posts',{as:bob,method:'POST',body:{text:'',image:uploaded.path},expect:201});assert.equal(imagePost.post.image,uploaded.path);assert.equal((await fetch(base+uploaded.path)).status,200);});
test('profile changes and data exports contain the right account only',async()=>{const result=await call('/me',{as:bob,method:'PATCH',body:{name:'Bob Updated',bio:'Building something good.',location:'Dublin',color:'#c3e1ea'}});assert.equal(result.user.name,'Bob Updated');const exported=await call('/me/export',{as:bob});assert.equal(exported.profile.id,bob.user.id);assert.ok(exported.posts.every(p=>p.author.id===bob.user.id));assert.ok(exported.messages.every(m=>m.sender_id===bob.user.id));assert.equal(exported.profile.password,undefined);});
test('invalid objects, unknown recipients, bad reactions and cross-site writes return clear errors',async()=>{await call('/posts',{as:bob,method:'POST',body:null,expect:400});await call('/conversations',{as:bob,method:'POST',body:{},expect:400});await call(`/posts/${post.id}/like`,{as:bob,method:'POST',body:{active:'true'},expect:400});await call('/posts',{as:bob,method:'POST',body:{text:'cross-site'},headers:{Origin:'https://another-site.example'},expect:403});});
test('database and sessions survive a full server restart',async()=>{await stop();await start();assert.equal((await call('/session',{as:bob})).user.name,'Bob Updated');assert.equal((await call(`/posts/${post.id}`,{as:bob})).post.text,'An edited persistent test post.');assert.equal((await call(`/conversations/${thread}/messages`,{as:bob})).messages.length,2);});
test('password changes invalidate other sessions and logout removes access',async()=>{const other=await call('/auth/login',{method:'POST',body:{handle:'bob_test',password:'  password with spaces  '}});await call('/me/password',{as:bob,method:'POST',body:{current:'wrong',next:'new-password'},expect:400});await call('/me/password',{as:bob,method:'POST',body:{current:'  password with spaces  ',next:'new-bob-password'}});assert.equal((await call('/session',{as:other})).user,null);const next=await call('/auth/login',{method:'POST',body:{handle:'bob_test',password:'new-bob-password'}});await call('/auth/logout',{as:next,method:'POST'});assert.equal((await call('/session',{as:next})).user,null);});
