import React,{useState} from 'react';
import {UserPlus,MessageCircle,Check,X,UsersRound,ArrowRight} from 'lucide-react';
import {ProfileLink,Avatar,SearchField,Empty,Loading,Modal} from '../components/UI.jsx';
export function FriendButton({person,onFriend}){
  const [busy,setBusy]=useState(false),[confirm,setConfirm]=useState(false);const r=person.relation;
  async function act(action){setBusy(true);try{await onFriend(person,action);setConfirm(false);}finally{setBusy(false);}}
  const control=r==='incoming'?<div className="friend-actions"><button className="button primary tiny" disabled={busy} onClick={()=>act('accept')}><Check size={15}/> Accept</button><button className="icon-button" disabled={busy} aria-label={`Decline ${person.name}`} onClick={()=>act('decline')}><X size={17}/></button></div>:<button className={`button ${r==='friends'?'connected':'secondary'} tiny`} disabled={busy} onClick={()=>r==='friends'?setConfirm(true):act(r==='outgoing'?'cancel':'request')}>{r==='friends'?<><Check size={15}/> Friends</>:r==='outgoing'?'Cancel request':<><UserPlus size={15}/> Add friend</>}</button>;
  return <>{control}{confirm?<Modal title={`Remove ${person.name}?`} onClose={()=>setConfirm(false)}><p className="muted">This person will leave your friends feed. Your conversation will stay available.</p><div className="dialog-actions"><button className="button secondary" onClick={()=>setConfirm(false)}>Keep friend</button><button className="button danger" disabled={busy} onClick={()=>act('remove')}>{busy?'Removing…':'Remove friend'}</button></div></Modal>:null}</>;
}
export default function Friends({people,navigate,onFriend,onMessage,loading}){const [tab,setTab]=useState('all'),[query,setQuery]=useState('');const list=people.filter(p=>(tab==='all'||tab==='friends'&&p.relation==='friends'||tab==='requests'&&['incoming','outgoing'].includes(p.relation))&&`${p.name} ${p.handle} ${p.bio}`.toLowerCase().includes(query.toLowerCase()));const incoming=people.filter(p=>p.relation==='incoming').length;return <><div className="page-title"><h1>Your people</h1><p>Old friends, new faces, better conversations.</p></div><div className="tabs"><button className={tab==='all'?'active':''} onClick={()=>setTab('all')}>Discover</button><button className={tab==='friends'?'active':''} onClick={()=>setTab('friends')}>Friends <span>{people.filter(p=>p.relation==='friends').length}</span></button><button className={tab==='requests'?'active':''} onClick={()=>setTab('requests')}>Requests {incoming?<span className="tab-count">{incoming}</span>:null}</button></div><SearchField value={query} onChange={setQuery} placeholder="Find your people"/>{loading?<Loading/>:list.length?<div className="people-list">{list.map(p=><article className="person-row" key={p.id}><ProfileLink user={p} navigate={navigate}/><p className="person-bio">{p.bio}</p><div className="person-actions"><FriendButton person={p} onFriend={onFriend}/><button className="icon-button" aria-label={`Message ${p.name}`} onClick={()=>onMessage(p)}><MessageCircle size={19}/></button></div>{p.relation==='incoming'?<span className="request-label">Sent you a friend request</span>:null}</article>)}</div>:<Empty icon={UsersRound} title={query?'No matching people':tab==='friends'?'Your circle starts here':'No requests waiting'}>{query?'Try a name or handle.':tab==='friends'?'Explore the directory and send a friend request.':'When someone reaches out, you’ll find them here.'}</Empty>}</>;}
export function SearchResults({query,people,...props}){const list=people.filter(p=>`${p.name} ${p.handle} ${p.bio}`.toLowerCase().includes(query.toLowerCase()));return <><div className="page-title"><h1>Search results</h1><p>Looking for “{query}”</p></div><h2 className="section-label">People</h2>{list.length?<div className="search-people">{list.slice(0,8).map(p=><div key={p.id}><ProfileLink user={p} navigate={props.navigate}/><FriendButton person={p} onFriend={props.onFriend}/></div>)}</div>:<p className="muted small">No matching people. Try another name.</p>}<h2 className="section-label">Posts</h2>{props.children}</>;}
