import React,{useState} from 'react';
import {MessageSquare,ArrowRight,Eye,EyeOff} from 'lucide-react';
import {api} from '../lib/api.js';
export default function Auth({demo,onLogin}){
  const [mode,setMode]=useState('login'),[form,setForm]=useState({name:'',handle:'',password:''}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[show,setShow]=useState(false);
  async function submit(e){e.preventDefault();setBusy(true);setError('');try{const result=await api(`/auth/${mode}`,{method:'POST',body:form});onLogin(result.user);}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function explore(){setBusy(true);setError('');try{onLogin((await api('/auth/demo',{method:'POST'})).user);}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <main className="auth-page"><div className="auth-story"><div className="wordmark"><MessageSquare size={30}/> social.</div><div><h1>Your people.<br/>A little closer.</h1><p>A place for the everyday moments,<br/>the unfinished ideas, and the conversations<br/>that make it all worthwhile.</p></div><figure><img src="./countryside.webp" alt="A winding path through green hills"/><figcaption>Take the scenic route.</figcaption></figure></div><section className="auth-form-wrap"><form onSubmit={submit}><h2>{mode==='login'?'Good to see you.':'Make yourself at home.'}</h2><p className="muted">{mode==='login'?'Sign in and pick up where you left off.':'Create an account in your social space.'}</p>{mode==='register'?<label>Your name<input required autoComplete="name" minLength={2} maxLength={60} value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Alex Morgan"/></label>:null}<label>Handle<div className="handle-input"><span>@</span><input required autoComplete="username" maxLength={24} minLength={mode==='register'?3:1} pattern={mode==='register'?'[a-zA-Z0-9_]+':undefined} value={form.handle} onChange={e=>setForm({...form,handle:e.target.value.replace(/^@/,'')})} placeholder="your_handle"/></div></label><label>Password<div className="password-input"><input required autoComplete={mode==='login'?'current-password':'new-password'} minLength={mode==='register'?8:1} maxLength={128} type={show?'text':'password'} value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder={mode==='register'?'At least 8 characters':'Your password'}/><button type="button" aria-label={show?'Hide password':'Show password'} onClick={()=>setShow(!show)}>{show?<EyeOff size={19}/>:<Eye size={19}/>}</button></div></label>{error?<p className="form-error" role="alert">{error}</p>:null}<button disabled={busy} className="button primary auth-submit">{busy?'One moment…':mode==='login'?'Sign in':'Create account'}<ArrowRight size={18}/></button><p className="auth-switch">{mode==='login'?'New here?':'Already have an account?'} <button type="button" onClick={()=>{setMode(mode==='login'?'register':'login');setError('');}}>{mode==='login'?'Create an account':'Sign in'}</button></p>{demo?<><div className="auth-divider"><span>or take a look around</span></div><button type="button" disabled={busy} className="button secondary auth-submit" onClick={explore}>Explore the demo <ArrowRight size={18}/></button><p className="small muted demo-note">Sample people, real working features. Demo changes are saved on this server.</p></>:null}</form><p className="auth-footer">A smaller space. Better conversations.</p></section></main>;
}
