import React,{useEffect,useRef} from 'react';
import {X,Search,LoaderCircle,ArrowRight,MessageCircle} from 'lucide-react';
export function Avatar({user,size='normal'}){const initials=(user?.name||'?').trim().split(/\s+/).slice(0,2).map(n=>n[0]).join('').toUpperCase();return <span className={`avatar ${size}`} style={{background:user?.color||'#d5e7de'}}>{user?.avatar?<img src={user.avatar} alt={user.name}/>:initials}</span>;}
export function ProfileLink({user,navigate,children,className=''}){return <button className={`profile-link ${className}`} onClick={()=>navigate(`/profile/${user.id}`)}>{children||<><Avatar user={user}/><span><strong>{user.name}</strong><small>@{user.handle}</small></span></>}</button>;}
export function Modal({title,children,onClose,wide=false}){const ref=useRef(null);useEffect(()=>{const old=document.activeElement,overflow=document.body.style.overflow;document.body.style.overflow='hidden';ref.current.focus();return()=>{document.body.style.overflow=overflow;old?.focus();};},[]);function key(e){if(e.key==='Escape')onClose();if(e.key==='Tab'){const els=[...ref.current.querySelectorAll('button,input,select,textarea,a[href]')].filter(el=>!el.disabled),first=els[0],last=els.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className={`modal ${wide?'wide':''}`} ref={ref} tabIndex={-1} role="dialog" aria-modal="true" aria-label={title} onKeyDown={key}><header><h2>{title}</h2><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X size={21}/></button></header>{children}</section></div>;}
export function Empty({icon:Icon=MessageCircle,title,children,action,onAction}){return <div className="empty"><Icon size={36}/><h2>{title}</h2><p>{children}</p>{action?<button className="button primary" onClick={onAction}>{action}<ArrowRight size={17}/></button>:null}</div>;}
export function ErrorState({message,onRetry}){return <div className="error-state" role="alert"><p>{message}</p><button className="button secondary" onClick={onRetry}>Try again</button></div>;}
export function Loading({label='Loading…'}){return <div className="loading" role="status"><LoaderCircle className="spin" size={23}/>{label}</div>;}
export function SearchField({value,onChange,placeholder='Search',label=placeholder}){return <label className="search-field"><Search size={18}/><input aria-label={label} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>;}
